Feature/migration product
victorpessoa1/beacademy-devstart-agua-marinha pull request #15
Opened 2022-07-01 12:27 UTC by Francielabreu

2022-07-01 12:52 UTC, BrunoApostolico requested changes

2022-07-01 12:52 UTC, BrunoApostolico commented on projeto-empresarial/database/migrations/2022_07_01_013154_create_products_table.php
> +            $table->string('price',100);
Sugiro alteração do tipo flutuante com tamanho 8 e 4 casas decimais, conforme diagrama do Banco.

$table->float('price',8,4);

2022-07-01 12:52 UTC, BrunoApostolico commented on projeto-empresarial/database/migrations/2022_07_01_013154_create_products_table.php
> +            $table->string('quantity',100);
Sugiro alteração do tipo flutuante com tamanho 8 e 6 casas decimais, conforme diagrama do Banco.

$table->float('quantity',8,6);

2022-07-01 12:52 UTC, BrunoApostolico commented on projeto-empresarial/database/migrations/2022_07_01_013154_create_products_table.php
> +            $table->string('saleprice',100);
Sugiro alteração do tipo flutuante com tamanho 8 e 4 casas decimais, conforme diagrama do Banco.

$table->float('saleprice',8,4);

2022-07-01 20:55 UTC, EstefanyS2 requested changes
altere Product para Products!

2022-07-01 20:55 UTC, EstefanyS2 commented on projeto-empresarial/app/Models/Product.php
> +class Product extends Model
Products

2022-07-01 22:28 UTC, Francielabreu commented on projeto-empresarial/app/Models/Product.php
> +class Product extends Model
O projeto esta sendo escrito com os termos em inglês , então foi criado a model Product e a migrate por padrão já veio como products

2022-07-02 12:22 UTC, BrunoApostolico approved these changes

2022-07-02 18:59 UTC, EstefanyS2 approved these changes

2022-07-03 13:55 UTC, merged